apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot-sample-app
  name: springboot-sample-app
  namespace: fha-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-sample-app
    spec:
      containers:
        - image: fouadhamdi/springboot-sample-app:1.0.1
          name: springboot-sample-app
          resources: {}
status: {}
